import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-4xl mx-auto`}
      >
        <header className="flex justify-between items-center gap-4 max-w-4xl mx-auto">
          <h1>Nazmul hasan</h1>
          <nav className="flex gap-4">
            <Link href={'/medi'}>Medi</Link>
            <Link href={'/products'}>Product</Link>
            <Link href={'/profile'}>Profile</Link>
            <Link href={'/dashboard'}>Dashboard</Link>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
